### ISSUE TITLE
When running cleanup in integration tests, it should check if the resource is actually gone

### ISSUE THREAD

**Issue by MattHodge** [OctopusDeploy/go-octopusdeploy#1]
<a href="https://github.com/MattHodge"><img src="https://avatars0.githubusercontent.com/u/1966555?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [MattHodge](https://github.com/MattHodge)**
_Tuesday Jul 03, 2018 at 21:14 GMT_
_Originally opened as https://github.com/MattHodge/go-octopusdeploy/issues/7_

----

Currently, the `clean` function for integration tests doesn't query Octopus Deploy to check if the resource has actually been deleted, so a test can silently fail.

The `clean` functions should be made to verify that the resource has been deleted by trying to do a `get` against the resource.

**Comment by jbristowe** [comment]
Added in integration tests.
