### ISSUE TITLE
Use HyperMedia API instead of hard-coded paths.

### ISSUE THREAD

**Issue by jeff-french** [OctopusDeploy/go-octopusdeploy#10]
It would be good to use the hypermedia API instead of hard coding the path. Change to the paths has been very rare (as customers have been hard coding as well), but we've done it at least once.

_Originally posted by @droyad in https://github.com/OctopusDeploy/go-octopusdeploy/pull/8_

**Comment by jbristowe** [comment]
Implemented support for hypermedia in the Beta. 😃
