### ISSUE TITLE
Fetching all Projects in a project group

### ISSUE THREAD

**Issue by tomas-mota** [OctopusDeploy/go-octopusdeploy#132]
**Is your feature request related to a problem? Please describe.**
The following endpoint exists in the api: "/api/projectgroups/{id}/projects"

**Describe the solution you'd like**
I would like to be able to fetch all projects in a project group through this package, which so far I have not been able to do concisely. Perhaps I am missing something?

**Comment by jbristowe** [comment]
Has you tried [GetProjects](https://github.com/OctopusDeploy/go-octopusdeploy/blob/main/pkg/projectgroups/project_group_service.go#L111)?

**Comment by tomas-mota** [comment]
Oh that is part of V2, I was still using V1 :) thanks for the help
