### ISSUE TITLE
Ability to call runbook run?

### ISSUE THREAD

**Issue by rayterrill** [OctopusDeploy/go-octopusdeploy#142]
**Is your feature request related to a problem? Please describe.**
Is there coverage for submitting a run book run? Perhaps I missed it?

**Describe the solution you'd like**
Clean API method to submit runbook with parameters, etc.

**Describe alternatives you've considered**
Currently implementing with REST call

**Additional context**
N/A

**Comment by benPearce1** [comment]
Hi @rayterrill,

It is possible to run a Runbook from the Go client, see the CLI for an example of how to call the endpoint from the client. This will need your server to be at 2022.3 or later.
