### ISSUE TITLE
[BUG] Unable to update a project variable that is binded

### ISSUE THREAD

**Issue by Matroxt** [OctopusDeploy/go-octopusdeploy#177]
**Description**
Using [tenants.UpdateVariables()](https://github.com/OctopusDeploy/go-octopusdeploy/blob/a8ebad1e53bd4155e574affbf9b09a723abcbbad/pkg/tenants/tenant_service.go#L249), I don't appear to be able to update the value of a given variable if it is binded.

**Steps To Reproduce**
1. Create a project variable
2. Set a value and [bind](https://octopus.com/docs/projects/variables/variable-substitutions#binding-variables) that new variable to another one
3. Try to update the value using the Golang SDK.
    1. I've been using `core.NewPropertyValue()`, then `UpdateVariables()`
4. Notice that the value didn't change.

**Expected Behavior**
The value is updated with the desired one.

**Any Logs and/or Other Supporting Information**
The SDK doesn't return any errors

**Environment and/or Versions**
- Octopus Server Version: `2022.3.10723`
- Go Version: `go1.19.1 darwin/arm64`

**Comment by benPearce1** [comment]
Hi @Matroxt ,

I have not being able to recreate your issue, but I have extended one of the [tests](https://github.com/OctopusDeploy/go-octopusdeploy/blob/cbfee5237ec864519d52fc7fe26ba5d219f3d24e/test/e2e/tenant_service_test.go#L77) to validate an update to a tenant variable with a binding syntax (https://github.com/OctopusDeploy/go-octopusdeploy/pull/179). This is currently passing, but maybe I have not got the exact same scenario that you are having trouble with.

Are you able to provide a code example and an explanation of the setup that you are having trouble with?

Thanks

**Comment by Matroxt** [comment]
Hi,

I ended up circumventing the problem by first deleting the template ID with `delete(vars.ProjectVariables[projID].Variables[envID], template.ID)`, pushing back `vars` to Octopus, then updating the value and pushing it back to Octopus. Basically two `UpdateVariables()` calls.

Probably not the answer you were looking for, but I don't have much time in this end of the year to figure out why it's not working, sorry about that.

We can close this if you want to avoid cluttering the issue board.
