### ISSUE TITLE
json: cannot unmarshal object into Go struct field DeploymentActionResource.Properties of type octopusdeploy.PropertyValueResource

### ISSUE THREAD

**Issue by MattHodge** [OctopusDeploy/go-octopusdeploy#2]
<a href="https://github.com/MattHodge"><img src="https://avatars0.githubusercontent.com/u/1966555?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [MattHodge](https://github.com/MattHodge)**
_Tuesday Jul 03, 2018 at 21:38 GMT_
_Originally opened as https://github.com/MattHodge/go-octopusdeploy/issues/8_

----

**Comment by MattHodge** [comment]
<a href="https://github.com/droyad"><img src="https://avatars0.githubusercontent.com/u/1687639?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [droyad](https://github.com/droyad)**
_Monday Nov 12, 2018 at 04:17 GMT_

----

See https://github.com/MattHodge/terraform-provider-octopusdeploy/issues/6#issuecomment-437748551 for how the API serializes these values

**Comment by jeff-french** [comment]
Fixed with #12
