### ISSUE TITLE
Standardize on a method of pagination

### ISSUE THREAD

**Issue by MattHodge** [OctopusDeploy/go-octopusdeploy#4]
<a href="https://github.com/MattHodge"><img src="https://avatars0.githubusercontent.com/u/1966555?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [MattHodge](https://github.com/MattHodge)**
_Wednesday Oct 24, 2018 at 10:08 GMT_
_Originally opened as https://github.com/MattHodge/go-octopusdeploy/issues/34_

----

Newer versions of the Octopus Deploy API support querying for a large number of records using `?take=`, for example: `lifecycles?take=2147483647`

This can prevent multiple queries against an Octopus Deploy server but doesn't work in older versions of the API.

Is there a way a helper method can be provided for pagination to save having to do it per resource?

**Comment by jbristowe** [comment]
Supported in beta, along with other query string parameters (`skip`, `take`, etc.).
