### ISSUE TITLE
Replace validation with custom implementation

### ISSUE THREAD

**Issue by MattHodge** [OctopusDeploy/go-octopusdeploy#5]
<a href="https://github.com/MattHodge"><img src="https://avatars0.githubusercontent.com/u/1966555?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [MattHodge](https://github.com/MattHodge)**
_Wednesday Oct 24, 2018 at 10:10 GMT_
_Originally opened as https://github.com/MattHodge/go-octopusdeploy/issues/35_

----

Some parts of the code base are using the `go-playground/validator.v9` package to validating structs.

Switch over to using our own version of validation (already used for `projects`)

**Comment by jbristowe** [comment]
We decided to stick with the `go-playground/validator` package for the time being. This allows us to validate structs through struct tags. It also supports extensibility, which we are leveraging for various models.
