### ISSUE TITLE
Support Project Conversion

### ISSUE THREAD

**Issue by jbristowe** [OctopusDeploy/go-octopusdeploy#57]
Endpoint: /projects/{projectId}/versioncontrol/convert

**Comment by benPearce1** [comment]
This has been implemented. See https://github.com/OctopusDeploy/go-octopusdeploy/blob/main/pkg/projects/convert_to_vcs.go and https://github.com/OctopusDeploy/cli/blob/main/pkg/cmd/project/convert/convert.go#L201
